### ISSUE TITLE
Image size management

### ISSUE THREAD

**Issue by philip-murdoch** [NrsSystems/docs#35]
Now that I'm adding screenshots of the management panes, they look enormous on a mobile device and even on a laptop they make the page scroll beyond the window width. Even when I have an image cropped down to just the relevant part of the screen, as under [Schedules Management - Add a Special Event](https://docs.xsponse.com/digital-displays/schedules-management#add-a-special-event), they're still disproportionately large.

I can think of three ways to manage this:

1. I (or Dallas) can create thumbnail versions that we use in the page code but set as hyperlinks to full-size versions; this has the drawback of leaving the person just on the large image itself and needing to click Back in the browser to return.
2. Similar to 1, using thumbnails, but link to a documentation page with the full-size image embedded; this allows us to include the regular navigation links on the page and all that.
3. Maybe there's some clever way to use CSS/YAML/JavaScript/whatever to manage clickable thumbnails that pop-up full-size versions as overlays on the documentation page? Or some other neat trick?

**Comment by philip-murdoch** [comment]
I glanced at a couple Microsoft documentation pages to find an example of how they handle it; in their [Power Apps Mobile](https://docs.microsoft.com/en-us/powerapps/mobile/run-powerapps-on-mobile#early-access-feature) documentation, there's an instance of a large image that's in its own scrolling box within the main page column. I have no idea whether that sort of thing is more advanced than what we want to do with our page coding.

**Comment by kyle-nrs** [comment]
The Microsoft documentation in question is actually two images, side by side in a table that allows scrolling. The images are always that size. I personally don't like that option, since we are showing the desktop layout and that won't fit nicely on a mobile screen.

Option 1 is as simple as setting a CSS property (that probably should have been set in the first place). With that property, it will fit in the page as a "thumbnail version". Then someone can right click/hold-press to open the full size image in a new tab. The only problem is I don't know if that is common knowledge or not. Worst case scenario there though is they just pinch zoom on their current page.

Option 1 as thumbnail:
![image](https://user-images.githubusercontent.com/45835963/114466187-f86c9080-9b9c-11eb-8fc2-5fdef92bb2ba.png)

**Comment by philip-murdoch** [comment]
Ooh yeah, let's do the simple CSS option, that sounds great. I can just add a note below the screenshots saying something to the effect of "right-click or press and hold to view larger".

Let me know when you've made that change, please, then I'll add in captions. Thanks!

**Comment by kyle-nrs** [comment]
I just uploaded the CSS option. I'll let you close the issue when you are done with the changes that you want to make.

**Comment by philip-murdoch** [comment]
It turns out press-hold doesn't work on iPhones at least, in that it doesn't offer to open the image in a new tab; it only offers Share, Add to Photos, or Copy. So the only choice would be to use the zoom gesture on the page. Still, it's obviously far better to have the images fit the column width so this is still a worthwhile solution.

**Comment by philip-murdoch** [comment]
For reference, this is the text I added:
_To view larger: on a computer, right-click and select "open in new tab"; on a mobile touchscreen, use the zoom gesture._
